spring:
  cloud:
    stream:
      bindings:
        myInput:
          destination: stepTopics
          group: daily
      kafka:
        binder:
          brokers: localhost:9094
          producer-properties:
            key.serializer: org.apache.kafka.common.serialization.StringSerializer
            value.serializer: org.apache.kafka.common.serialization.StringSerializer
          consumer-properties:
            key.deserializer: org.apache.kafka.common.serialization.StringDeserializer
            value.deserializer: org.apache.kafka.common.serialization.StringDeserializer
  redis:
    host: localhost
    port: 6379
    password: password